const A = {
  CREATE_ITEM: "CREATE_ITEM",
  DELETE_ITEM: "DELETE_ITEM",

  SAVE_ITEM_WITH_PROMISE: "SAVE_ITEM_WITH_PROMISE",
  SAVE_ITEM_WITH_PROMISE_PENDING: `SAVE_ITEM_WITH_PROMISE_PENDING`,
  SAVE_ITEM_WITH_PROMISE_FULFILLED: `SAVE_ITEM_WITH_PROMISE_FULFILLED`,
  SAVE_ITEM_WITH_PROMISE_REJECTED: `SAVE_ITEM_WITH_PROMISE_REJECTED`,

  NEW_CAT_FACT_ITEM: "NEW_CAT_FACT_ITEM",
  NEW_CAT_FACT_ITEM_PENDING: `NEW_CAT_FACT_ITEM_PENDING`,
  NEW_CAT_FACT_ITEM_FULFILLED: `NEW_CAT_FACT_ITEM_FULFILLED`,
  NEW_CAT_FACT_ITEM_REJECTED: `NEW_CAT_FACT_ITEM_REJECTED`
};

type Item = {
  id: number;
  description: string;
};

export type DefaultState = {
  items: Item[];
  loading: boolean;
};

export default A;
