export const DELETE_CAT_FACT = "DELETE_CAT_FACT";
export const NEW_CAT_FACT = "NEW_CAT_FACT";
export const NEW_CAT_FACT_PENDING = `NEW_CAT_FACT_PENDING`;
export const NEW_CAT_FACT_FULFILLED = `NEW_CAT_FACT_FULFILLED`;
export const NEW_CAT_FACT_REJECTED = `NEW_CAT_FACT_REJECTED`;
